example1com-memcached:
  build: ../../Memcached/
  command: /usr/bin/memcached -m 8 -c 256 -b 256 -R 200 -t 4 -n 72 -f 1.25 -o modern

example1com-nginx:
  build: ../../Nginx/
  command: /start.sh
  volumes:
    - "/home/hostings/example1.com/html:/var/www/html:rw"
    - "/home/hostings/example1.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
  ports:
    - "9001:80"
    - "9443:443"
  expose:
    - 80
    - 443
  links:
    - example1com-memcached

example2com-memcached:
  build: ../../Memcached/
  command: /usr/bin/memcached -m 8 -c 256 -b 256 -R 200 -t 4 -n 72 -f 1.25 -o modern

example2com-nginx:
  build: ../../Nginx/
  command: /start.sh
  volumes:
    - "/home/hostings/example2.com/html:/var/www/html:rw"
    - "/home/hostings/example2.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
  ports:
    - "9002:80"
    - "9444:443"
  expose:
    - 80
    - 443
  links:
    - example2com-memcached
