example1com-memcached:
  build: ../../Memcached/
  command: /usr/bin/memcached

example1com-nginx:
  build: ../../Nginx/
  command: /start.sh
  volumes:
    - "/home/hostings/example1.com/html:/var/www/html:rw"
    - "/home/hostings/example1.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
  ports:
    - "9001:80"
    - "9443:443"
  expose:
    - 80
    - 443
  links:
    - example1com-memcached



example2com-memcached:
  build: ../../Memcached/
  command: /usr/bin/memcached

example2com-nginx:
  build: ../../Nginx/
  command: /start.sh
  volumes:
    - "/home/hostings/example2.com/html:/var/www/html:rw"
    - "/home/hostings/example2.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
  ports:
    - "9002:80"
    - "9444:443"
  expose:
    - 80
    - 443
  links:
    - example2com-memcached
