memcached:
  build: ../../Memcached/
  command: /usr/bin/memcached

nginx-php-fpm:
  build: ../../Nginx/
  command: /start.sh
  volumes:
    - "/home/hostings/example1.com/html:/var/www/html:rw"
    - "/home/hostings/example1.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
  ports:
    - "9001:80"
    - "9443:443"
  expose:
    - 80
    - 443
  links:
    - memcached
