version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "9005:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  example1com-memcached:
    build: ../../Memcached/
    command: /usr/bin/memcached -m 8 -c 256 -b 256 -R 200 -t 4 -n 72 -f 1.25 -o modern

  example1com-nginx:
    build: ../../Nginx/
    command: /start.sh
    container_name: example1.com
    volumes:
      - "/home/hostings/example1.com/html:/var/www/html:rw"
      - "/home/hostings/example1.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
    links:
      - example1com-memcached:memcached
    environment:
      - VIRTUAL_HOST=example1.com
      - VIRTUAL_PORT=80

  example2com-memcached:
    build: ../../Memcached/
    command: /usr/bin/memcached -m 8 -c 256 -b 256 -R 200 -t 4 -n 72 -f 1.25 -o modern

  example2com-nginx:
    build: ../../Nginx/
    command: /start.sh
    container_name: example2.com
    volumes:
      - "/home/hostings/example2.com/html:/var/www/html:rw"
      - "/home/hostings/example2.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
    links:
      - example2com-memcached:memcached
    environment:
      - VIRTUAL_HOST=example2.com
      - VIRTUAL_PORT=80
