---
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=example1.com

  example1com-memcached:
    build: ../../Memcached/
    command: /usr/bin/memcached -m 8 -c 256 -b 256 -R 200 -t 4 -n 72 -f 1.25 -o modern
    restart: always
    container_name: example1.com-mc
  example1com-nginx:
    build: ../../Nginx/
    command: /start.sh
    container_name: example1.com
    restart: always
    volumes:
      - "/home/hostings/example1.com/html:/var/www/html:rw"
      - "/home/hostings/example1.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
    links:
      - example1com-memcached:memcached
    environment:
      - VIRTUAL_HOST=example1.com
      - VIRTUAL_PORT=80

  example2com-memcached:
    build: ../../Memcached/
    command: /usr/bin/memcached -m 8 -c 256 -b 256 -R 200 -t 4 -n 72 -f 1.25 -o modern
    restart: always
    container_name: example2.com-mc
  example2com-nginx:
    build: ../../Nginx/
    command: /start.sh
    container_name: example2.com
    restart: always
    volumes:
      - "/home/hostings/example2.com/html:/var/www/html:rw"
      - "/home/hostings/example2.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
    links:
      - example2com-memcached:memcached
    environment:
      - VIRTUAL_HOST=example2.com
      - VIRTUAL_PORT=80

  example3com-memcached:
    build: ../../Memcached/
    command: /usr/bin/memcached -m 8 -c 256 -b 256 -R 200 -t 4 -n 72 -f 1.25 -o modern
    restart: always
    \container_name: example3.com-mc
  example3com-nginx:
    build: ../../Nginx/
    command: /start.sh
    container_name: example3.com
    restart: always
    volumes:
      - "/home/hostings/example3.com/html:/var/www/html:rw"
      - "/home/hostings/example3.com/extra.conf.d:/etc/nginx/extra.conf.d/:rw"
    links:
      - example3com-memcached:memcached
    environment:
      - VIRTUAL_HOST=example3.com
      - VIRTUAL_PORT=80
